# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Form.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def __init__(self):
        # self.setupUi(?)
        pass

    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(693, 429)
        self.formLayoutWidget = QtWidgets.QWidget(Form)
        self.formLayoutWidget.setGeometry(QtCore.QRect(49, 19, 561, 291))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.userNameLabel = QtWidgets.QLabel(self.formLayoutWidget)
        self.userNameLabel.setObjectName("userNameLabel")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.userNameLabel)
        self.userNameLineEdit = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.userNameLineEdit.setObjectName("userNameLineEdit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.userNameLineEdit)
        self.userPassLabel = QtWidgets.QLabel(self.formLayoutWidget)
        self.userPassLabel.setObjectName("userPassLabel")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.userPassLabel)
        self.userPassLineEdit = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.userPassLineEdit.setObjectName("userPassLineEdit")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.userPassLineEdit)
        self.pushButton = QtWidgets.QPushButton(self.formLayoutWidget)
        self.pushButton.setObjectName("pushButton")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.pushButton)
        self.btnLogin = QtWidgets.QPushButton(self.formLayoutWidget)
        self.btnLogin.setObjectName("btnLogin")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.btnLogin)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def onLogin(self):
        userName = self.userNameLineEdit.text()
        print(userName)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.userNameLabel.setText(_translate("Form", "UserName"))
        self.userPassLabel.setText(_translate("Form", "User Pass"))
        self.pushButton.setText(_translate("Form", "Cancel"))
        self.btnLogin.setText(_translate("Form", "Login"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)

    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)

    ui.btnLogin.clicked.connect(ui.onLogin)




    Form.show()
    sys.exit(app.exec_())
